### ISSUE TITLE
Minute is incorrectly extracted

### ISSUE THREAD

**Issue by Abasz** [lswiderski/MiScaleBodyComposition#1]
I think when the _data byte[] is parsed, the minute is not set correctly extracted (it is set to the address of the second):

```cs
Day = _data[5],
Month = _data[4],
Hour = _data[6],
Minute = _data[8],
```
According to this https://github.com/wiecosystem/Bluetooth/blob/master/doc/devices/huami.health.scale2.md the minute's address is the 7 and 8 is the second.

**Comment by lswiderski** [comment]
Fixed in #2
